### ISSUE TITLE
ModuleNotFoundError: No module named 'plugins'

### ISSUE THREAD

**Issue by luthfirrahmanb** [airflow-plugins/google_analytics_plugin#9]
Hi guys, thank you for you awesome job for the community, i've a little problem, when importing  `from plugins.google_analytics_plugin.hooks.google_analytics_hook import GoogleAnalyticsHook` to my custom operator to cloud storage. And it give me an error message `ModuleNotFoundError: No module named 'plugins'`. What I do is like on this tutorial [https://github.com/astronomer/airflow-guides/blob/master/guides/google-analytics-to-redshift.md](url) , thank you

**Comment by pingdink** [comment]
We have the same issue
